PROYECTOISW/Controllers/FavoritosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PROYECTOISW.Models;
using PROYECTOISW.Models.ViewModel.PerfilViewModel;
using System.Security.Claims;

namespace PROYECTOISW.Controllers
{
    public class FavoritosController : Controller
    {
        private readonly ProyectoiswContext _contexto;
        public FavoritosController(ProyectoiswContext contexto)
        {
            _contexto = contexto;
        }

        #region Mostrar Favoritos
        [HttpGet]
        public async Task<IActionResult> Mostrar()
        {
            //Deserealizar la cookie y obtener id de usuario
            var claimsIdentity = User.Identity as ClaimsIdentity;
            var idUser = claimsIdentity?.FindFirst("Id_Usuario")?.Value;
            if (idUser != null)
            {
                var propiedadesFavoritas = await _contexto.Favoritos
                    .Where(f => f.IdUsuario == int.Parse(idUser))
                    .Include(f => f.IdPropiedadNavigation)
                    .ThenInclude(p => p.Imagenes)
                    .Select(f => f.IdPropiedadNavigation)
                    .ToListAsync();
                return View(propiedadesFavoritas);
            }
            return View();

        }
        #endregion

        #region Crear Favoritos
        [HttpGet]
        public async Task<IActionResult> Favoritos(int idPropiedad)
        {
            //Verificar que el favorito no exista
            var encontrado = await _contexto.Favoritos.Where(id => id.IdPropiedad == idPropiedad).FirstOrDefaultAsync();
            if (encontrado != null)
            {
                return Content("");
            }
            var claimsIdentity = User.Identity as ClaimsIdentity;
            var idUser = claimsIdentity?.FindFirst("Id_Usuario")?.Value;
            Favorito f = new Favorito();
            f.IdPropiedad = idPropiedad;
            f.IdUsuario = int.Parse(idUser);
            await _contexto.Favoritos.AddAsync(f);
            await _contexto.SaveChangesAsync();
            return Content("");
        }
        #endregion

        #region Eliminar
        [HttpPost]
        public async Task<IActionResult> Eliminar(int idPropiedad)
        {
            var favorito = await _contexto.Favoritos
                .FirstOrDefaultAsync(f => f.IdPropiedad == idPropiedad);

            if (favorito != null)
            {
                _contexto.Favoritos.Remove(favorito);
                await _contexto.SaveChangesAsync();
                return Json(new { success = true, idPropiedad = idPropiedad });
            }

            return Json(new { success = false });
        }
        #endregion
    }
}

PROYECTOISW/Controllers/PropiedadesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using PROYECTOISW.Models;
using System.IO;

//Agregar using
using Microsoft.AspNetCore.Authorization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Newtonsoft.Json.Linq;
using System.Security.Claims;
using System.Text.RegularExpressions;
using PROYECTOISW.Models.ViewModel.PropiedadViewModel;
using PROYECTOISW.Models.ViewModel.PerfilViewModel;
using System.Reflection.Metadata.Ecma335;
using NuGet.Protocol.Plugins;
using PROYECTOISW.Servicios;
using Microsoft.AspNetCore.Razor.Language.CodeGeneration;

namespace PROYECTOISW.Controllers
{
    [Authorize]
    public class PropiedadesController : Controller
    {
        private readonly ProyectoiswContext _contexto;
        private readonly IServicioRC _servicios;

        public PropiedadesController(ProyectoiswContext contexto, IWebHostEnvironment hostingEnvironment, IServicioRC servicios)
        {
            _contexto = contexto;
            _servicios = servicios;
        }

        #region Crear
        [Authorize(Roles = "P")]
        [HttpGet]
        public IActionResult CrearPropiedad()
        {
            var model = new CrearPropiedadViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CrearPropiedad(CrearPropiedadViewModel nuevo)
        {
            if (ModelState.IsValid)
            {
                //Deseralizar una cookie
                var claimsIdentity = User.Identity as ClaimsIdentity;
                if (claimsIdentity != null)
                {
                    var id = int.Parse(claimsIdentity.FindFirst("Id_Usuario")?.Value);
                    // System.Diagnostics.Debug.WriteLine("Se subieron fotos\n");
                    var crear = new Propiedade
                    {
                        Estado = "H",
                        IdUsuario = id,
                        Titulo = nuevo.Titulo,
                        Descripcion = nuevo.Descripcion,
                        TipoPropiedad = nuevo.TipoPropiedad,
                        PrecioRenta = nuevo.PrecioRenta,
                        Superficie = nuevo.Superficie,
                        NumeroHabitaciones = nuevo.NumeroHabitaciones,
                        NumeroBaños = nuevo.NumeroBaños,
                        Servicios = nuevo.Servicios,
                        Direccion = nuevo.Direccion,
                        Distancia = nuevo.Distancia,
                        CondicionesEspeciales = nuevo.CondicionesEspeciales,
                        FechaPublicacion = DateTime.Now,
                    };
                    _contexto.Propiedades.Add(crear);
                    await _contexto.SaveChangesAsync();
                    //Valida que no sean más de 10 imagenes
                    if (nuevo.archivosImagenes.Count > 10)
                    {
                        ViewBag.Imagenes = "No se permiten más de 10 imagenes";
                        return View(nuevo);
                    }

                    if (nuevo.archivosImagenes != null && nuevo.archivosImagenes.Count > 0)
                    {
                        foreach (var foto in nuevo.archivosImagenes)
                        {
                            if (foto.Length > 0)
                            {
                                using (var memoryStream = new MemoryStream())
                                {
                                    await foto.CopyToAsync(memoryStream);
                                    var imagen = new Imagene
                                    {
                                        IdPropiedad = crear.IdPropiedad,
                                        Imagen = memoryStream.ToArray()
                                    };
                                    _contexto.Imagenes.Add(imagen);
                                }
                            }
                        }
                        await _contexto.SaveChangesAsync();
                    }
                    return RedirectToAction("Index", "Home", new { id = id, opcion = 0 });
                }
            }
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            foreach (var error in errors)
            {
                System.Diagnostics.Debug.WriteLine(error.ErrorMessage);
            }
            return View(nuevo);
        }
        #endregion

        #region MostrarPrpopiedades
        [HttpGet]
        public async Task<IActionResult> GestionarPropiedades()
        {
            // Esta vista contendrá todas las publicaciones realizadas por el propietario
            // en donde cada propiedad tendrá botones para que el usuario pueda editar, eliminar o poner 
            // en suspensión una publicación
            // 1. Hay que consultar el id del propietario en la cookie
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                try
                {
                    var id = Convert.ToInt32(claimsIdentity.FindFirst("Id_Usuario")?.Value);
                    var propiedades = await _contexto.Propiedades
                        .Where(e => e.IdUsuario == id)
                        .Include(p => p.Imagenes) // Incluye las imágenes relacionadas
                        .Include(p => p.Duda) // Incluye las reseñas relacionadas
                        .ToListAsync();

                    return View(propiedades);
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
            return View();
        }
        #endregion

        #region Editar Propiedad
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            try
            {
                var propiedades = await _contexto.Propiedades
                       .Where(e => e.IdPropiedad == id)
                       .Include(p => p.Imagenes) // Incluye las imágenes relacionadas
                       .FirstOrDefaultAsync();
                var editar = new EditarPropiedadViewModel();
                editar.Titulo = propiedades.Titulo;
                editar.Descripcion = propiedades.Descripcion;
                editar.TipoPropiedad = propiedades.TipoPropiedad;
                editar.PrecioRenta = propiedades.PrecioRenta;
                editar.Superficie = propiedades.Superficie;
                editar.NumeroHabitaciones = propiedades.NumeroHabitaciones;
                editar.NumeroBaños = propiedades.NumeroBaños;
                editar.Servicios = propiedades.Servicios;
                editar.Direccion = propiedades.Direccion;
                editar.Distancia = propiedades.Distancia;
                editar.CondicionesEspeciales = propiedades.CondicionesEspeciales;
                editar.Data = new List<byte[]>();

                foreach (var item in propiedades.Imagenes)
                {
                    editar.Data.Add(item.Imagen);
                }

                return View(editar);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Editar(EditarPropiedadViewModel editar)
        {
            if (ModelState.IsValid)
            {
                var imagenes = await _contexto.Imagenes.Where(i => i.IdPropiedad == editar.Id).ToListAsync();
              

                await _contexto.Propiedades
                       .Where(d => d.IdPropiedad == editar.Id)
                       .ExecuteUpdateAsync(setters =>
                       setters.SetProperty(t =>
                       t.Titulo, editar.Titulo)
                       .SetProperty(t => t.Descripcion, editar.Descripcion)
                       .SetProperty(t => t.TipoPropiedad, editar.TipoPropiedad)
                       .SetProperty(t => t.PrecioRenta, editar.PrecioRenta)
                       .SetProperty(t => t.Superficie, editar.Superficie)
                       .SetProperty(t => t.NumeroHabitaciones, editar.NumeroHabitaciones)
                       .SetProperty(t => t.NumeroBaños, editar.NumeroBaños)
                       .SetProperty(t => t.Servicios, editar.Servicios)
                       .SetProperty(t => t.Direccion, editar.Direccion)
                       .SetProperty(t => t.Distancia, editar.Distancia)
                       .SetProperty(t => t.CondicionesEspeciales, editar.CondicionesEspeciales
                       ));
                await _contexto.SaveChangesAsync();

                //agregar las fotos
                if (editar.archivosImagenes != null && editar.archivosImagenes.Count > 0)
                {
                    if (imagenes.Count == 10)
                    {
                        ViewBag.Imagenes = "El número maximo de imagenes por proiedad es 10.";
                        return View(editar);
                    }
                    foreach (var foto in editar.archivosImagenes)
                    {
                        if (foto.Length > 0)
                        {
                            using (var memoryStream = new MemoryStream())
                            {
                                await foto.CopyToAsync(memoryStream);
                                var imagen = new Imagene
                                {
                                    IdPropiedad = editar.Id,
                                    Imagen = memoryStream.ToArray()
                                };
                                _contexto.Imagenes.Add(imagen);
                            }
                        }
                    }
                    await _contexto.SaveChangesAsync();
                }

PROYECTOISW/Views/Shared/_Layout.cshtml
@* @model PROYECTOISW.Models.ViewModel.PerfilViewModel.UsuarioViewModel *@
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PROYECTOISW</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PROYECTOISW.styles.css" asp-append-version="true" />
    <style>
        .nav-link .bi-search {
            color: green; /* Color oscuro */
            width: 50px;
            height: 50px;
        }
        /* CSS */
        .nav-item .dropdown-menu {
            display: none;
            position: absolute;
            background-color: #f8f9fa;
            min-width: 160px;
            box-shadow: 0 8px 16px rgba(0,0,0,0.2);
            z-index: 1;
        }

        .nav-item:hover .dropdown-menu {
            display: block;
        }

        .miImagen {
            width: 100px; /* Ajusta el tamaño de la imagen según tus necesidades */
            height: 100px;
            border-radius: 50%; /* Hace que la imagen sea circular */
        }

        .d-flex.align-items-center {
            display: flex;
            align-items: center;
            margin-bottom: 60px; 
        }

        .ms-3 {
            margin-left: 1rem; /* Ajusta el espacio entre la imagen y el nombre */
        }
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $.ajax({
                url: '@Url.Action("CheckAlquiladas", "Home")',
                type: 'GET',
                success: function(data) {
                    if (data.tienePropiedadesAlquiladas) {
                        $('#alquiladas-link').show();
                    }
                }
            });
        });
    </script>
</head>
<body>
    <div class="contenedor">
        <div class="miHeader">
            <nav class="navbar navbar-expand-md navbar-light bg-light">
                <div class="container-fluid">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse flex-column align-items-center" id="navbarNav">
                        <div class="d-flex align-items-center">
                            <img src="@Url.Action("ObtenerImagen", "Usuario")" alt="Foto de perfil" class="miImagen" />
                            <p class="ms-3 mb-0">@User.Identity.Name</p>
                        </div>
                        <ul class="navbar-nav flex-column">
                            <!-- Evalua el rol del usuario -->
                            @if (User.IsInRole("A"))
                            {
                                <li class="nav-item">
                                    <a href="@Url.Action("Busqueda", "Busqueda")" class="nav-link text-dark">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0" />
                                        </svg>
                                        Buscar Propiedades
                                    </a>
                                </li>
                                <li class="nav-item" id="alquiladas-link" style="display:none;">
                                    <a href="@Url.Action("Rentadas", "Busqueda")" class="nav-link text-dark">Propiedades Alquiladas</a>
                                </li>
                                <li class="nav-item"><a href="@Url.Action("Mostrar", "Favoritos")" class="nav-link text-dark">Favoritos</a></li>
                            }
                            else if (User.IsInRole("P"))
                            {
                                <li class="nav-item"><a href="@Url.Action("CrearPropiedad", "Propiedades")" class="nav-link text-dark">Agregar Propiedad</a></li>
                                <li class="nav-item"><a href="@Url.Action("GestionarPropiedades", "Propiedades")" class="nav-link text-dark">Gestionar Propiedades</a></li>
                            }
                            <!-- Configuracion del perfil -->
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Configuración de perfil
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="@Url.Action("CambiarContraseña", "Usuario")">Actualizar Contraseña</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("CambiarCorreo", "Usuario")">Actualizar Correo</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("CambiarTelefono", "Usuario")">Actualizar Teléfono</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("CambiarImagen", "Usuario")">Actualizar Foto de Perfil</a></li>
                                </ul>
                            </li>
                            <li class="nav-item"><a href="@Url.Action("CerrarSesion","Usuario")" class="nav-link text-dark">Cerrar Sesión</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="miMain container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PROYECTOISW/Views/Shared/_MyLayout.cshtml
@model PROYECTOISW.Models.ViewModel.PerfilViewModel.UsuarioViewModel
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Perfil</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/css/Perfil.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PROYECTOISW.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <div class="sidebar">
            <!--Imagen del usuario-->
            @{
                var base64 = Convert.ToBase64String(Model.Foto);
                var imgSrc = $"data:image/jpeg;base64,{base64}";
                <img src="@imgSrc" alt="Alternate Text" class="imagenPerfil" />
            }
            <h5>@Model.NombreCompleto</h5>
            <ul class="menu">
                <!--Evalua el rol del usuario -->
                @if (User.IsInRole("A"))
                {
                    <li><a href="#" data-target="#main-content" data-url="@Url.Action("Busqueda", "Busqueda")">Buscar Propiedades</a></li>
                    <li><a href="#" data-target="#main-content" data-url="@Url.Action("Rentadas", "Busqueda")">Propiedades Alquiladas</a></li>
                    <li><a href="#" data-target="#main-content" data-url="@Url.Action("Mostrar", "Favoritos")">Favoritos</a></li>
                }
                else if (User.IsInRole("P"))
                {
                    <li><a href="#" data-target="#main-content" data-url="@Url.Action("CrearPropiedad","Propiedades")">Agregar Propiedad</a></li>
                    <li><a href="#" data-target="#main-content" data-url="@Url.Action("GestionarPropiedades", "Propiedades")">Gestionar Propiedades</a></li>
                }
                <!--Configuracion del perfil-->
                <li>
                    <a href="#">Configuración de Perfil</a>
                    <ul class="submenu">
                        <li><a href="#" data-target="#main-content" data-url="@Url.Action("CambiarContraseña", "Usuario")">Actualizar Contraseña</a></li>
                        <li><a href="#" data-target="#main-content" data-url="@Url.Action("CambiarCorreo", "Usuario")">Actualizar Correo</a></li>
                        <li><a href="#" data-target="#main-content" data-url="@Url.Action("CambiarTelefono", "Usuario")">Actualizar Teléfono</a></li>
                      @*   <li><a href="#" data-target="#main-content" data-url="@Url.Action("CambiarImagen", "Usuario")">Actualizar Foto de Perfil</a></li> *@
                    </ul>
                </li>
            </ul>
            <ul class="logout">
                <li><a href="@Url.Action("CerrarSesion","Usuario")">Cerrar Sesión</a></li>
            </ul>
        </div>
        <div id="main-content" class="main-content">
            @RenderBody()
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function() {
            $('a[data-target]').on('click', function(e) {
                e.preventDefault();
                var target = $(this).data('target');
                var url = $(this).data('url');
                if (url) {
                    $(target).load(url, function(response, status, xhr) {
                        if (status == "error") {
                            var msg = "Sorry but there was an error: ";
                            $(target).html(msg + xhr.status + " " + xhr.statusText);
                        }
                    });
                }
            });
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>