PROYECTOISW/Models/ViewModel/RCViewModel/ValidarCorreoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PROYECTOISW.Models.ViewModels.RCViewModels
{
    public class ValidarCorreoViewModel
    {
        [Required(ErrorMessage = "El campo es requerido")]
        [EmailAddress(ErrorMessage = "El correo no es valido")]
        [Display(Name = "Correo Electrónico")]
        public string? Correo { get; set; }
    }
}

PROYECTOISW/Models/ViewModel/RCViewModel/ValidarTokenViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace PROYECTOISW.Models.ViewModels.RCViewModels
{
    public class ValidarTokenViewModel
    {
        [Required(ErrorMessage = "El campo es requerido")]
        [Display(Name = "Ingresa el código")]
        public string? Token { get; set; }
        
        public string? Correo { get; set; }
    }
}

PROYECTOISW/Controllers/RcController.cs
using Microsoft.AspNetCore.Mvc;
using PROYECTOISW.Servicios;
using PROYECTOISW.Models.ViewModels.RCViewModels;
using PROYECTOISW.Models.ViewModel;

namespace PROYECTOISW.Controllers
{
    public class RcController : Controller
    {
        private readonly IServicioRC _servicioRC;
        public RcController(IServicioRC servicioRC)
        {
            _servicioRC = servicioRC;
        }

        #region Validar Correo
        [HttpGet]
        public IActionResult ValidarCorreo()
        {
            return View();
        }
        [HttpPost]
        public IActionResult ValidarCorreo(ValidarCorreoViewModel recuperar)
        {
            //Cifra el token
            string token = GenerarToken();

            if (ModelState.IsValid)
            {
                var encontrado = _servicioRC.BuscarCorreo(recuperar.Correo);

                if (encontrado == null)
                {
                    ViewBag.Invalido = "El correo no esta registrado en el sistema";
                    return View(recuperar);
                }
                //Genera toquen
                _servicioRC.GuardarToken(Cifrado.GetSHA256(token), encontrado);
                //Mandar alerta de nuevo token
                _servicioRC.EnviarCorreo(encontrado, token);
                var model = new TokenContraseña();
                model.ValidarTokenViewModel = new ValidarTokenViewModel();
                model.CambiarContrase =  new CambiarContraseñaViewModel();
                model.ValidarTokenViewModel.Correo = recuperar.Correo;
                model.CambiarContrase.Correo = recuperar.Correo;
                return View("ValidarToken", model);
            }
            return View();
        }
        #endregion

        #region Validar Token
        [HttpGet]
        public IActionResult ValidarToken()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ValidarToken(TokenContraseña model)
        {
            if (model.ValidarTokenViewModel != null)
            {
                // Busca el token con un correo y tokens válidos
                if (await _servicioRC.ValidarCon(model.ValidarTokenViewModel.Correo, Cifrado.GetSHA256(model.ValidarTokenViewModel.Token)) == false)
                {
                    ViewBag.Invalido = "Código no válido.";
                    ViewBag.TokenValido = false;
                    return View(model);
                }
                ViewBag.TokenValido = true;
                return View(model);
                //return View("RestablecerContraseña", new CambiarContraseñaViewModel { Correo = validar.Correo, Token = validar.Token });
            }
            ViewBag.Invalido = "";
            ViewBag.TokenValido = false;
            return View();
        }
        #endregion

        #region Restablecer Contraseña
        [HttpGet]
        public IActionResult RestablecerContraseña()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> RestablecerContraseña(TokenContraseña model)
        {
            if (model.CambiarContrase != null)
            {
                //Restablecer contraseña
                await _servicioRC.ActualizarCon(Cifrado.GetSHA256(model.CambiarContrase.Nueva), model.CambiarContrase.Correo);
                ViewBag.Contrase = "Contraseña restablecida con exito";
                return RedirectToAction("IniciarSesion","Usuario");
            }
            return View(model);
        }
        #endregion

        public string GenerarToken()
        {
            Random random = new Random();
            int token = random.Next(1000, 9000);
            return token.ToString();
        }
    }
}

PROYECTOISW/Views/Rc/RestablecerContraseña.cshtml
@model PROYECTOISW.Models.ViewModels.RCViewModels.CambiarContraseñaViewModel
@{
    Layout = null;
    ViewData["Title"] = "Nueva Contraseña";
}
<!DOCTYPE html>
<html>
<head lang="es">
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - PROYECTOISW</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PROYECTOISW.styles.css" asp-append-version="true" />
</head>
<body>
    <div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
        <div style="background-color: white; padding: 2rem; border-radius: 10px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); width: 100%; max-width: 400px;">
            <h2 style="text-align: center; ">Cambiar Contraseña</h2>
            <form asp-action="RestablecerContraseña" asp-controller="Rc" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="Correo" type="hidden" />
                @*    <input asp-for="Token" type="hidden" /> *@
                <div class="mb-5">
                    <label asp-for="Nueva" class="form-label" style="color: #28a745;"></label>
                    <input asp-for="Nueva" class="form-control" type="password" placeholder="Ingresar contraseña" />
                    <span asp-validation-for="Nueva" class="text-danger"></span>
                </div>
                <div class="mb-5">
                    <label asp-for="Confirmar" class="form-label" style="color: #28a745;"></label>
                    <input asp-for="Confirmar" class="form-control" type="password" placeholder="Confirmar contraseña" />
                    <span asp-validation-for="Confirmar" class="text-danger"></span>
                </div>
                <div class="mb-5 text-center">
                    <button type="submit" class="btn btn-secondary" style="background-color: #28a745; border-color: #28a745;">Confirmar</button>
                </div>
                <!-- Mensaje de error -->
                @if (!string.IsNullOrEmpty(ViewBag.Incorrecto))
                {
                    <div class="alert alert-danger mt-3" role="alert">
                        @ViewBag.Incorrecto
                    </div>
                }
                @if (!string.IsNullOrEmpty(ViewBag.Contrase))
                {
                    <div class="alert alert-danger mt-3" role="alert">
                        @ViewBag.Contrase
                    </div>
                }
            </form>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

</body>
</html>

PROYECTOISW/Views/Rc/ValidarCorreo.cshtml
@model PROYECTOISW.Models.ViewModels.RCViewModels.ValidarCorreoViewModel
@{
    Layout = null;
    ViewData["Title"] = "Recuperar Cuenta";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - PROYECTOISW</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PROYECTOISW.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="miForm container">
        <h1 class="text-center" style="color: black;">Recuperación de Contraseña</h1>
        <form asp-action="ValidarCorreo" asp-controller="Rc" method="post" class="w-50">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-4">
                <label asp-for="Correo" class="form-label" style="color: black;">Correo Electrónico</label>
                <input asp-for="Correo" class="form-control" placeholder="Ingresar Correo Electrónico" type="email" style="border-color: #28a745;" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>
            <div class="mb-4 text-center">
                <button type="submit" class="btn" style="background-color: #28a745; color: white; border: none;">Enviar Código</button>
            </div>

            <!-- Mensaje de error -->
            @if (!string.IsNullOrEmpty(ViewBag.Invalido))
            {
                <div class="alert alert-danger mt-3" role="alert">
                    @ViewBag.Invalido
                </div>
            }
        </form>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @*   <script>
        document.addEventListener('DOMContentLoaded', function () {
            const correo = document.getElementById('correo');
            const contraseña = document.getElementById('contraseña');
            const entrar = document.getElementById('entrar');

            function checkInputs() {
                if (correo.value.trim() !== '' && contraseña.value.trim() !== '') {
                    entrar.disabled = false;
                } else {
                    entrar.disabled = true;
                }
            }

            correo.addEventListener('input', checkInputs);
            contraseña.addEventListener('input', checkInputs);
        });
    </script> *@
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

</body>
</html>

PROYECTOISW/Views/Rc/ValidarToken.cshtml
@model PROYECTOISW.Models.ViewModel.TokenContraseña
@{
    Layout = null;
    ViewData["Title"] = "Token";
}
<!DOCTYPE html>
<html>
<head lang="es">
    <meta charset="utf-8" />
    <title>@ViewData["Title"] - PROYECTOISW</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PROYECTOISW.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="principal">
        <div class="container form1">
            <h2 style="text-align: center; color: black; font-size: 1.8rem;">Validar Token</h2>
            <form asp-action="ValidarToken" method="post" style="line-height: 1.8;">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="ValidarTokenViewModel.Correo" type="hidden" />
                <div class="mb-5">
                    <label asp-for="ValidarTokenViewModel.Token" class="form-label" style="color: #28a745; font-size: 1.2rem;">Ingresar el código</label>
                    <input asp-for="ValidarTokenViewModel.Token" class="form-control" placeholder="Ingresar Token" type="text" style="font-size: 1rem;" />
                    <span asp-validation-for="ValidarTokenViewModel.Token" class="text-danger"></span>
                </div>
                <div class="mb-5 text-center">
                    <button type="submit" class="btn btn-secondary" style="background-color: #28a745; border-color: #28a745; color: white; font-size: 1rem; padding: 0.5rem 1rem;">Verificar Código</button>
                </div>
                @if (!string.IsNullOrEmpty(ViewBag.Invalido))
                {
                    <div class="alert alert-danger" role="alert" style="font-size: 1rem;">
                        @ViewBag.Invalido
                    </div>
                }
            </form>
        </div>
        <div class="container form2">
            <h2 style="text-align: center; ">Cambiar Contraseña</h2>
            <form asp-action="RestablecerContraseña" asp-controller="Rc" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="CambiarContrase.Correo" type="hidden" value="@Model.ValidarTokenViewModel.Correo"/>
                <div class="mb-5">
                    <label asp-for="CambiarContrase.Nueva" class="form-label" style="color: #28a745;"></label>
                    <input asp-for="CambiarContrase.Nueva" id="password1" class="form-control" type="password" placeholder="Ingresar contraseña" />
                    <span asp-validation-for="CambiarContrase.Nueva" class="text-danger"></span>
                </div>
                <div class="mb-5">
                    <label asp-for="CambiarContrase.Confirmar" class="form-label" style="color: #28a745;"></label>
                    <input asp-for="CambiarContrase.Confirmar" id="password2" class="form-control" type="password" placeholder="Confirmar contraseña" />
                    <span asp-validation-for="CambiarContrase.Confirmar" class="text-danger"></span>
                </div>
                <div class="mb-5 text-center">
                    <button type="submit" id="submitButton" class="btn btn-secondary" style="background-color: #28a745; border-color: #28a745;">Confirmar</button>
                </div>
                <!-- Mensaje de error -->
               @*  @if (!string.IsNullOrEmpty(ViewBag.Contrase))
                {
                    <div class="alert alert-danger mt-3" role="alert">
                        @ViewBag.Contrase
                    </div>
                } *@
            </form>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function() {
            var tokenValido = '@ViewBag.TokenValido' === 'True';
            if (!tokenValido) {
                $('#password1, #password2, #submitButton').prop('disabled', true);
            } else {
                $('#password1, #password2, #submitButton').prop('disabled', false);
            }
        });
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
</body>
</html>